name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          channel: stable

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Start Emulator
        run: |
          sudo apt-get install qemu-kvm -y
          echo "hw.cpu.ncore=2" >> $ANDROID_SDK_ROOT/emulator/emulator.cfg
          $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-audio -no-window &
          android-wait-for-emulator
          adb shell settings put global window_animation_scale 0 &
          adb shell settings put global transition_animation_scale 0 &
          adb shell settings put global animator_duration_scale 0 &

      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: swetry.apk
          path: app/build/outputs/apk/debug/app-debug.apk
